# Site settings
title: "myRA - my Retirement Account"
email: myra@treasury.gov
description: "myRA is a retirement savings account for individuals looking for a simple, safe and affordable way to save for their retirement. There will be no fees to open and maintain a myRA and the account will never lose value. The investment will be backed by the United States Treasury. Soon, individuals will be able to open myRA accounts and begin contributing to them every payday. myRA will be initially offered through participating employers."
baseurl: /myra
url: "https://myra.treasury.gov"

# Build settings
markdown: kramdown
permalink: pretty
exclude: ['LICENSE.md', README.md]
sass:
  sass_dir: static/_sass
